apiVersion: apps/v1
kind: Deployment
metadata:
  name: common
  labels:
    app: common
spec:
  replicas: 3
  selector:
    matchLabels:
      app: common
  template:
    metadata:
      labels:
        app: common
    spec:
      containers:
      - name: common-service
        image: dhdudwn95/common:22
        ports:
        - containerPort: 8082
        resources:
          requests:
            cpu: 50m
---
apiVersion: v1
kind: Service
metadata:
  name: common
spec:
  type: NodePort
  ports:
    - nodePort: 30082
      port: 8082       # 서비스 포트
      targetPort: 8082   # 타켓, 즉 pod의 포트
      protocol: TCP
      name: http
  selector:
    app: common
